# Generated by Django 4.2.11 on 2024-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSite', '0002_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='qualifications',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
