# Generated by Django 4.2.11 on 2024-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSite', '0003_jobpost_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requirements',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
